version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: predictus-db
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: predictus
      POSTGRES_PASSWORD: predictus123
      POSTGRES_DB: predictus
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
